export const bichos = {
    avestruz: require("../../../assets/bichos/avestruz.png"),
    aguia: require("../../../assets/bichos/aguia.png"),
    burro: require("../../../assets/bichos/burro.png"),
    borboleta: require("../../../assets/bichos/borboleta.png"),
    cachorro: require("../../../assets/bichos/cachorro.png"),
    cabra: require("../../../assets/bichos/cabra.png"),
    carneiro: require("../../../assets/bichos/carneiro.png"),
    camelo: require("../../../assets/bichos/camelo.png"),
    cobra: require("../../../assets/bichos/cobra.png"),
    coelho: require("../../../assets/bichos/coelho.png"),
    cavalo: require("../../../assets/bichos/cavalo.png"),
    elefante: require("../../../assets/bichos/elefante.png"),
    galo: require("../../../assets/bichos/galo.png"),
    gato: require("../../../assets/bichos/gato.png"),
    jacare: require("../../../assets/bichos/jacare.png"),
    leao: require("../../../assets/bichos/leao.png"),
    macaco: require("../../../assets/bichos/macaco.png"),
    porco: require("../../../assets/bichos/porco.png"),
    pavao: require("../../../assets/bichos/pavao.png"),
    peru: require("../../../assets/bichos/peru.png"),
    touro: require("../../../assets/bichos/touro.png"),
    tigre: require("../../../assets/bichos/tigre.png"),
    urso: require("../../../assets/bichos/urso.png"),
    veado: require("../../../assets/bichos/veado.png"),
    vaca: require("../../../assets/bichos/vaca.png"),
}
